### ISSUE TITLE
Replay Mod getting flagged by Chrome/Edge etc as having a virus

### ISSUE THREAD

**Issue by pattheflip** [kkots/ggxrd_replay_mod#1]
FYI - not sure when this happened, but yesterday I was able to use the Replay Mod just fine, and today it seems to not only have disappeared from my PC shortly after opening it, but when I try to download it, it gets flagged as having a virus in Chrome and Edge.

**Comment by kkots** [comment]
I'll try to get this fixed (thankfully I have a laptop with another copy of Windows). In the meantime, it should be possible to add an exclusion for it in Windows Defender or whatever antivirus you use.

**Comment by kkots** [comment]
I did all I could, but it is still marked as a virus. I don't know if it will help, but you can vote on VirusTotal to increase community score of the latest version: https://www.virustotal.com/gui/file/9e1170d8438b27fa637cd3c11d5339b733ec84d26f52a825394a280e3a7855a1?nocache=1 (when I release a new version, which will be soon, all your votes will become meaningless).
The one antivirus out of 68 that gets triggered by this is called Bkav Pro. There have been many reports that it just flags everything and I can only assume that it's some extortion scheme to pay money to get added to their exclusion lists or something.
Sorry.
